#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias="ls -lah"

# misc/OS
alias ls='ls -GFhla'
alias showHidden='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideHidden='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
# docker
alias dc='docker-compose'
alias dcu='dc up'
alias dcd='dc down'
alias dls='docker ps -a -q'
alias drmcall='docker rm $(docker ps -a -q)'
alias drmiall='docker rmi $(docker images -a -q)'
alias dkillem='docker kill $(docker ps -a -q)'
alias dstop='docker stop $(docker ps -a -q)'
alias dp='docker ps'
alias dpa='docker ps -a'
# git
alias gs='git status '
alias ga='git add .'
alias gb='git branch'
alias gck='git checkout'
alias gll='git log -3 | cowsay | lolcat'
alias gl='git log'
alias gckm='git checkout master'
alias gms='git checkout master && git pull'
alias gc='git commit -m'
alias gpl='git pull'
alias gp='git push'
# alias gpr='BRANCH=\"$(git branch | grep \* | cut -d ' ' -f2)\" && git push --set-upstream origin $BRANCH'
alias bs='for branch in `git branch -r | grep -v HEAD`; do echo -e `git log -n1 --format="%an" $branch` \\t$branch; done | sort -r'

# jmeter
alias jm5='open /usr/local/bin/jmeter'
alias jm4='open /usr/local/bin/jmeter4/'

# mtc tasks
alias cdm='cd ~/dev/mtc'

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

# export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# added by travis gem
[ -f /Users/guyharwood/.travis/travis.sh ] && source /Users/guyharwood/.travis/travis.sh

# 25 July 2020
